//Player Tracking Pages Stats field and label collection for filter
if(typeof IS_PLAYER_TRACKING_PAGE != 'undefined'){
	window.customFilterColumns = [
		{ v: 'GP', k: 'GP', visible: true},
		{ v: 'MIN per game', k: 'MIN', visible: true},	

		{ v: 'Distance Traveled (total miles)', k: 'DIST', visible: true},
		{ v: 'Average Speed (mph)', k: 'AV_SPD', visible: true},
		{ v: 'Distance Traveled Per Game (miles)', k: 'DIST_PG', visible: true},
		{ v: 'Distance Traveled Per 48 Minutes (miles)', k: 'DIST_48', visible: true},

		{ v: 'Touches per game', k: 'TCH', visible: true},
		{ v: 'Total Touches', k: 'TCH_TOT', visible: true},
		{ v: 'Front Court Touches per game', k: 'FC_TCH', visible: true},
		{ v: 'Time of Possession (min)', k: 'TOP', visible: true},
		{ v: 'Close Touches per game', k: 'CL_TCH', visible: true},
		{ v: 'Elbow Touches per game', k: 'EL_TCH', visible: true},
		{ v: 'PTS per game', k: 'PTS', visible: true},
		{ v: 'PTS per Touch', k: 'PTS_TCH', visible: true},
		{ v: 'PTS Per Half Court Touch', k: 'PTS_HCCT', visible: true},

		{ v: 'AST per game', k: 'AST', visible: true},
		{ v: 'Passes per game', k: 'PASS', visible: true},
		{ v: 'Total AST', k: 'AST_TOT', visible: true},
		{ v: 'FT Assists per game', k: 'AST_FT', visible: true},
		{ v: 'Secondary Assists per game', k: 'AST_SEC', visible: true},
		{ v: 'Assist opportunities per game', k: 'AST_POT', visible: true},
		{ v: 'Points created by assist per game', k: 'PTS_CRT', visible: true},
		{ v: 'Points created by AST Per 48 Min', k: 'PTS_CRT_48', visible: true},

		{ v: 'STL per game', k: 'STL', visible: true},
		{ v: 'BLK per game', k: 'BLK', visible: true},
		{ v: 'Total BLK', k: 'BLK_TOT', visible: true},
		{ v: 'Opp FGM at Rim per game', k: 'FGM_DEFEND_RIM', visible: true},
		{ v: 'Opp FGA at Rim per game', k: 'FGA_DEFEND_RIM', visible: true},
		{ v: 'Opp FGP at Rim per game', k: 'FGP_DEFEND_RIM', visible: true},
	];	
}
else if(typeof IS_PLAYER_TRACKING_REBOUNDING_PAGE != 'undefined'){
	window.customFilterColumns = [	
		{ v: 'GP', k: 'GP', visible: true},
		{ v: 'MIN per game', k: 'MIN', visible: true},	
		{ v: 'REB per game', k: 'REB', visible: true},
		{ v: 'Percent Of rebounds per chance', k: 'REB_COL_PCT', visible: true},
		{ v: 'REB Chances per game', k: 'REB_CHANCE', visible: true},
		{ v: 'Total REB', k: 'REB_TOT', visible: true},
		{ v: 'Contested REB per game', k: 'REB_CONTESTED', visible: true},
		{ v: 'Uncontested REB per game', k: 'REB_UNCONTESTED', visible: true},
		{ v: 'Contested REB Percentage', k: 'REB_UNCONTESTED_PCT', visible: true},
	];		
}
//"FG_PCT","DPP_TOT","DVS","DPP","DTP","PTS_48"],
else if(typeof IS_PLAYER_TRACKING_DRIVE_PAGE != 'undefined'){
	window.customFilterColumns = [
		{ v: 'GP', k: 'GP', visible: true},
		{ v: 'MIN', k: 'MIN', visible: true},	
		{ v: 'FG% on Drives', k: 'FG_PCT', visible: true},
		{ v: 'Total Drives', k: 'DVS_TOT', visible: true},
		{ v: 'Total Player PTS on Drives', k: 'DPP_TOT', visible: true},
		{ v: 'Drives Per Game', k: 'DVS', visible: true},
		{ v: 'Player PPG on Drives', k: 'DPP', visible: true},
		{ v: 'Team PPG on Drives', k: 'DTP', visible: true},
		{ v: 'PTS Per 48 Min on Drives', k: 'PTS_48', visible: true},
	];
}
//"PTS_TOT","PTS","FGM","FGA","FG_PCT","FG3M","FG3A","FG3_PCT","EFG_PCT"]
else if(typeof IS_PLAYER_TRACKING_CATCH_SHOOT_PAGE != 'undefined'){
	window.customFilterColumns = [
		{ v: 'GP', k: 'GP', visible: true},
		{ v: 'MIN per game', k: 'MIN', visible: true},	
		{ v: 'Catch and Shoot Total PTS', k: 'PTS_TOT', visible: true},			
		{ v: 'Catch and Shoot PTS per game', k: 'PTS', visible: true},
		{ v: 'Catch and Shoot FGM per game', k: 'FGM', visible: true},
		{ v: 'Catch and Shoot FGA  per game', k: 'FGA', visible: true},
		{ v: 'Catch and Shoot FG%', k: 'FG_PCT', visible: true},
		{ v: 'Catch and Shoot 3FGM  per game', k: 'FG3M', visible: true},
		{ v: 'Catch and Shoot 3FGA  per game', k: 'FG3A', visible: true},
		{ v: 'Catch and Shoot 3FG%', k: 'FG3_PCT', visible: true},
		{ v: 'Catch and Shoot eFG%', k: 'EFG_PCT', visible: true},		
	];
}
//"PTS_TOT","PTS","FGM","FGA","FG_PCT","FG3M","FG3A","FG3_PCT","EFG_PCT"],
else if(typeof IS_PLAYER_TRACKING_PULLUP_PAGE != 'undefined'){
	window.customFilterColumns = [
		{ v: 'GP', k: 'GP', visible: true},
		{ v: 'Pull Up Shots MIN per game', k: 'MIN', visible: true},	
		{ v: 'Pull Up Shots Total PTS', k: 'PTS_TOT', visible: true},			
		{ v: 'Pull Up Shots PTS per game', k: 'PTS', visible: true},
		{ v: 'Pull Up Shots FGM per game', k: 'FGM', visible: true},
		{ v: 'Pull Up Shots FGA per game', k: 'FGA', visible: true},
		{ v: 'Pull Up Shots FG_PCT', k: 'FG_PCT', visible: true},
		{ v: 'Pull Up Shots FG3M per game', k: 'FG3M', visible: true},
		{ v: 'Pull Up Shots FG3A per game', k: 'FG3A', visible: true},
		{ v: 'Pull Up Shots FG3_PCT per game', k: 'FG3_PCT', visible: true},
		{ v: 'Pull Up Shots EFG_PCT per game', k: 'EFG_PCT', visible: true},		
	];
}
//"PTS","PTS_DRIVE","FGP_DRIVE","PTS_CLOSE","FGP_CLOSE","PTS_CATCH_SHOOT","FGP_CATCH_SHOOT","PTS_PULL_UP","FGP_PULL_UP","EFG_PCT"],
else if(typeof IS_PLAYER_TRACKING_SHOOTINGS_PAGE != 'undefined'){
	window.customFilterColumns = [
		{ v: 'GP', k: 'GP', visible: true},
		{ v: 'MIN per game', k: 'MIN', visible: true},	
		{ v: 'PTS per game', k: 'PTS', visible: true},
		{ v: 'Drives PTS', k: 'PTS_DRIVE', visible: true},
		{ v: 'Drives FG%', k: 'FGP_DRIVE', visible: true},
		{ v: 'Close Shots PTS per game', k: 'PTS_CLOSE', visible: true},
		{ v: 'Close Shots FG%', k: 'FGP_CLOSE', visible: true},
		{ v: 'Catch and Shoot PTS per game', k: 'PTS_CATCH_SHOOT', visible: true},		
		{ v: 'Catch and Shoot FG%', k: 'FGP_CATCH_SHOOT', visible: true},
		{ v: 'Pull Up Shots PTS per game', k: 'PTS_PULL_UP', visible: true},
		{ v: 'Pull Up FG%', k: 'FGP_PULL_UP', visible: true},
		{ v: 'eFG%', k: 'EFG_PCT', visible: true},				
	];
}
//Default
else{
	window.customFilterColumns = [
		{ v: 'GP', k: 'GP', visible: true},
		{ v: 'GS', k: 'GS', visible: true},
		{ v: 'MIN', k: 'MIN', visible: true},	
		{ v: 'W', k: 'W', visible: true},
		{ v: 'L', k: 'L', visible: true},
		{ v: 'Win%', k: 'W_PCT', visible: true},
		{ v: 'FGM', k: 'FGM', visible: true},
		{ v: 'FGA', k: 'FGA', visible: true},
		{ v: 'FG%', k: 'FG_PCT', visible: true},
		{ v: '3FGM', k: 'FG3M', visible: true},
		{ v: '3FGA', k: 'FG3A', visible: true},
		{ v: '3FG%', k: 'FG3_PCT', visible: true},
		{ v: 'FTM', k: 'FTM', visible: true},
		{ v: 'FTA', k: 'FTA', visible: true},
		{ v: 'FT%', k: 'FT_PCT', visible: true},
		{ v: 'OREB', k: 'OREB', visible: true},
		{ v: 'DREB', k: 'DREB', visible: true},
		{ v: 'REB', k: 'REB', visible: true},
		{ v: 'AST', k: 'AST', visible: true},
		{ v: 'TOV', k: 'TOV', visible: true},
		{ v: 'TO', k: 'TO', visible: true},
		{ v: 'STL', k: 'STL', visible: true},
		{ v: 'BLK', k: 'BLK', visible: true},
		{ v: 'BLKA', k: 'BLKA', visible: true},
		{ v: 'DD2', k: 'DD2', visible: true},
		{ v: 'TD3', k: 'TD3', visible: true},
		{ v: 'PF', k: 'PF', visible: true},
		{ v: 'PFD', k: 'PFD', visible: true},
		{ v: 'PTS', k: 'PTS', visible: true},
		{ v: '+/-', k: 'PLUS_MINUS', visible: true},
		{ v: 'OffRtg', k: 'OFF_RATING', visible: true},
		{ v: 'DefRtg', k: 'DEF_RATING', visible: true},
		{ v: 'NetRtg', k: 'NET_RATING', visible: true},
		{ v: 'AST%', k: 'AST_PCT', visible: true},
		{ v: 'AST/TO', k: 'AST_TO', visible: true},
		{ v: 'AST/TO', k: 'AST_TOV', visible: true},
		{ v: 'STL/TO', k: 'STL_TOV', visible: true},
		{ v: 'AST Ratio', k: 'AST_RATIO', visible: true},
		{ v: 'OREB%', k: 'OREB_PCT', visible: true},
		{ v: 'DREB%', k: 'DREB_PCT', visible: true},
		{ v: 'REB%', k: 'REB_PCT', visible: true},
		{ v: 'TO Ratio', k: 'TM_TOV_PCT', visible: true},
		{ v: 'eFG%', k: 'EFG_PCT', visible: true},
		{ v: 'TS%', k: 'TS_PCT', visible: true},
		{ v: 'USG%', k: 'USG_PCT', visible: true},
		{ v: 'PACE', k: 'PACE', visible: true},
		{ v: 'PIE', k: 'PIE', visible: true},
		{ v: 'FTA Rate', k: 'FTA_RATE', visible: true},
		{ v: 'Opp eFG%', k: 'OPP_EFG_PCT', visible: true},
		{ v: 'Opp FTA Rate', k: 'OPP_FTA_RATE', visible: true},
		{ v: 'Opp TO Ratio', k: 'OPP_TOV_PCT', visible: true},
		{ v: 'Opp OREB%', k: 'OPP_OREB_PCT', visible: true},
		{ v: 'PTS OFF TO', k: 'PTS_OFF_TOV', visible: true},
		{ v: '2nd PTS', k: 'PTS_2ND_CHANCE', visible: true},
		{ v: 'FBPs', k: 'PTS_FB', visible: true},
		{ v: 'PITP', k: 'PTS_PAINT', visible: true},
		{ v: 'Opp PTS OFF TO', k: 'OPP_PTS_OFF_TOV', visible: true},
		{ v: 'Opp 2nd PTS', k: 'OPP_PTS_2ND_CHANCE', visible: true},
		{ v: 'Opp FBPs', k: 'OPP_PTS_FB', visible: true},
		{ v: 'Opp PITP', k: 'OPP_PTS_PAINT', visible: true},
		{ v: '%FGA (2PT)', k: 'PCT_FGA_2PT', visible: true},
		{ v: '%FGA (3PT)', k: 'PCT_FGA_3PT', visible: true},
		{ v: '%PTS (2PT)', k: 'PCT_PTS_2PT', visible: true},
		{ v: '%PTS (2PT-MR)', k: 'PCT_PTS_2PT_MR', visible: true},
		{ v: '%PTS (3PT)', k: 'PCT_PTS_3PT', visible: true},
		{ v: '%PTS (FBPs)', k: 'PCT_PTS_FB', visible: true},
		{ v: '%PTS (FT)', k: 'PCT_PTS_FT', visible: true},
		{ v: '%PTS (OffTO)', k: 'PCT_PTS_OFF_TOV', visible: true},
		{ v: '%PTS (PITP)', k: 'PCT_PTS_PAINT', visible: true},
		{ v: '2FGM (%AST)', k: 'PCT_AST_2PM', visible: true},
		{ v: '2FGM (%UAST)', k: 'PCT_UAST_2PM', visible: true},
		{ v: '3FGM (%AST)', k: 'PCT_AST_3PM', visible: true},
		{ v: '3FGM (%UAST)', k: 'PCT_UAST_3PM', visible: true},
		{ v: 'FGM (%AST)', k: 'PCT_AST_FGM', visible: true},
		{ v: 'FGM (%UAST)', k: 'PCT_UAST_FGM', visible: true},
		{ v: 'Opp FGM', k: 'OPP_FGM', visible: true},
		{ v: 'Opp FGA', k: 'OPP_FGA', visible: true},
		{ v: 'Opp FG%', k: 'OPP_FG_PCT', visible: true},
		{ v: 'Opp 3FGM', k: 'OPP_FG3M', visible: true},
		{ v: 'Opp 3FGA', k: 'OPP_FG3A', visible: true},
		{ v: 'Opp 3FG%', k: 'OPP_FG3_PCT', visible: true},
		{ v: 'Opp FTM', k: 'OPP_FTM', visible: true},
		{ v: 'Opp FTA', k: 'OPP_FTA', visible: true},
		{ v: 'Opp FT%', k: 'OPP_FT_PCT', visible: true},
		{ v: 'Opp OREB', k: 'OPP_OREB', visible: true},
		{ v: 'Opp DREB', k: 'OPP_DREB', visible: true},
		{ v: 'Opp REB', k: 'OPP_REB', visible: true},
		{ v: 'Opp AST', k: 'OPP_AST', visible: true},
		{ v: 'Opp TO', k: 'OPP_TOV', visible: true},
		{ v: 'Opp STL', k: 'OPP_STL', visible: true},
		{ v: 'Opp BLK', k: 'OPP_BLK', visible: true},
		{ v: 'Opp BLKA', k: 'OPP_BLKA', visible: true},
		{ v: 'Opp PF', k: 'OPP_PF', visible: true},
		{ v: 'Opp PFD', k: 'OPP_PFD', visible: true},
		{ v: 'Opp PTS', k: 'OPP_PTS', visible: true},
		{ v: '%DREB', k: 'PCT_DREB', visible: true},
		{ v: '%3FGA', k: 'PCT_FG3A', visible: true},
		{ v: '%3FGM', k: 'PCT_FG3M', visible: true},
		{ v: '%FGA', k: 'PCT_FGA', visible: true},
		{ v: '%FGM', k: 'PCT_FGM', visible: true},
		{ v: '%FTA', k: 'PCT_FTA', visible: true},
		{ v: '%FTM', k: 'PCT_FTM', visible: true},
		{ v: '%OREB', k: 'PCT_OREB', visible: true},
		{ v: '%PF', k: 'PCT_PF', visible: true},
		{ v: '%PFD', k: 'PCT_PFD', visible: true},
		{ v: '%PTS', k: 'PCT_PTS', visible: true},
		{ v: '%REB', k: 'PCT_REB', visible: true},
		{ v: '%STL', k: 'PCT_STL', visible: true},
		{ v: '%TO', k: 'PCT_TOV', visible: true},
		{ v: '%AST', k: 'PCT_AST', visible: true},
		{ v: '%BLK', k: 'PCT_BLK', visible: true},
		{ v: '%BLKA', k: 'PCT_BLKA', visible: true},
		{ v: 'GS ON', k: 'GP-ON', visible: true},
		{ v: 'MIN ON', k: 'MIN-ON', visible: true},
		{ v: '+/- ON', k: 'PLUS_MINUS-ON', visible: true},
		{ v: 'OffRtg ON', k: 'OFF_RATING-ON', visible: true},
		{ v: 'DefRtg ON', k: 'DEF_RATING-ON', visible: true},
		{ v: 'NetRtg ON', k: 'NET_RATING-ON', visible: true},
		{ v: 'GS OFF', k: 'GP-OFF', visible: true},
		{ v: 'MIN OFF', k: 'MIN-OFF', visible: true},
		{ v: '+/- OFF', k: 'PLUS_MINUS-OFF', visible: true},
		{ v: 'OffRtg OFF', k: 'OFF_RATING-OFF', visible: true},
		{ v: 'DefRtg OFF', k: 'DEF_RATING-OFF', visible: true},
		{ v: 'NetRtg OFF', k: 'NET_RATING-OFF', visible: true},
		{ v: 'EFF', k: 'EFF', visible: true},

		{ v: 'FGM (<5ft)', k: 'FGM5ft1', visible: true},
		{ v: 'FGA (<5ft)', k: 'FGA5ft1', visible: true},
		{ v: 'FG% (<5ft)', k: 'FG_PCT5ft1', visible: true},
		{ v: 'FGM (5-9ft)', k: 'FGM5ft2', visible: true},
		{ v: 'FGA (5-9ft)', k: 'FGA5ft2', visible: true},
		{ v: 'FG% (5-9ft)', k: 'FG_PCT5ft2', visible: true},
		{ v: 'FGM (10-14ft)', k: 'FGM5ft3', visible: true},
		{ v: 'FGA (10-14ft)', k: 'FGA5ft3', visible: true},
		{ v: 'FG% (10-14ft)', k: 'FG_PCT5ft3', visible: true},
		{ v: 'FGM (15-19ft)', k: 'FGM5ft4', visible: true},
		{ v: 'FGA (15-19ft)', k: 'FGA5ft4', visible: true},
		{ v: 'FG% (15-19ft)', k: 'FG_PCT5ft4', visible: true},
		{ v: 'FGM (20-24ft)', k: 'FGM5ft5', visible: true},
		{ v: 'FGA (20-24ft)', k: 'FGA5ft5', visible: true},
		{ v: 'FG% (20-24ft)', k: 'FG_PCT5ft5', visible: true},
		{ v: 'FGM (25-29ft)', k: 'FGM5ft6', visible: true},
		{ v: 'FGA (25-29ft)', k: 'FGA5ft6', visible: true},
		{ v: 'FG% (25-29ft)', k: 'FG_PCT5ft6', visible: true},

		{ v: 'FGM (<8ft)', k: 'FGM8ft1', visible: true},
		{ v: 'FGA (<8ft)', k: 'FGA8ft1', visible: true},
		{ v: 'FG% (<8ft)', k: 'FG_PCT8ft1', visible: true},
		{ v: 'FGM (8-16ft)', k: 'FGM8ft2', visible: true},
		{ v: 'FGA (8-16ft)', k: 'FGA8ft2', visible: true},
		{ v: 'FG% (8-16ft)', k: 'FG_PCT8ft2', visible: true},
		{ v: 'FGM (16-24ft)', k: 'FGM8ft3', visible: true},
		{ v: 'FGA (16-24ft)', k: 'FGA8ft3', visible: true},
		{ v: 'FG% (16-24ft)', k: 'FG_PCT8ft3', visible: true},
		{ v: 'FGM (>24ft)', k: 'FGM8ft4', visible: true},
		{ v: 'FGA (>24ft)', k: 'FGA8ft4', visible: true},
		{ v: 'FG% (>24ft)', k: 'FG_PCT8ft4', visible: true},
		{ v: 'FGM (BackCourt)', k: 'FGM8ft5', visible: true},
		{ v: 'FGA (BackCourt)', k: 'FGA8ft5', visible: true},
		{ v: 'FG% (BackCourt)', k: 'FG_PCT8ft5', visible: true},

		{ v: 'FGM (RA)', k: 'FGMZone1', visible: true},
		{ v: 'FGA (RA)', k: 'FGAZone1', visible: true},
		{ v: 'FG% (RA)', k: 'FG_PCTZone1', visible: true},
		{ v: 'FGM (Non-RA)', k: 'FGMZone2', visible: true},
		{ v: 'FGA (Non-RA)', k: 'FGAZone2', visible: true},
		{ v: 'FG% (Non-RA)', k: 'FG_PCTZone2', visible: true},
		{ v: 'FGM (MidRange)', k: 'FGMZone3', visible: true},
		{ v: 'FGA (MidRange)', k: 'FGAZone3', visible: true},
		{ v: 'FG% (MidRange)', k: 'FG_PCTZone3', visible: true},
		{ v: 'FGM (Left Corner3)', k: 'FGMZone4', visible: true},
		{ v: 'FGA (Left Corner3)', k: 'FGAZone4', visible: true},
		{ v: 'FG% (Left Corner3)', k: 'FG_PCTZone4', visible: true},
		{ v: 'FGM (Right Corner3)', k: 'FGMZone5', visible: true},
		{ v: 'FGA (Right Corner3)', k: 'FGAZone5', visible: true},
		{ v: 'FG% (Right Corner3)', k: 'FG_PCTZone5', visible: true},
		{ v: 'FGM (AboveBR3)', k: 'FGMZone5', visible: true},
		{ v: 'FGA (AboveBR3)', k: 'FGAZone5', visible: true},
		{ v: 'FG% (AboveBR3)', k: 'FG_PCTZone5', visible: true},
	];
};

var playerCustomFilter = {
	name: "PlayerSearch",
	label: "Player Filter",
	type: "player",
	canRemove : true
};

var teamAbbrCustomFilter =	{
		name: "TeamAbbr",
		label: "Team Filter",
		type: "select",
		visible: true,
		disabled: false,
		activated: false,
		defaultValue : 'All',
		initialValue : 'All',
		multiSelect : true,
		canSearch: true,
		options : [
			{ k:"0",  v: "All"},
			{ k: "ATL", v: "Atlanta Hawks" },
			{ k: "BOS", v: "Boston Celtics" },
			{ k: "BKN", v: "Brooklyn Nets" },
			{ k: "CHA", v: "Charlotte Bobcats" },
			{ k: "CHI", v: "Chicago Bulls" },
			{ k: "CLE", v: "Cleveland Cavaliers" },
			{ k: "DAL", v: "Dallas Mavericks" },
			{ k: "DEN", v: "Denver Nuggets" },
			{ k: "DET", v: "Detroit Pistons" },
			{ k: "GSW", v: "Golden State Warriors" },
			{ k: "HOU", v: "Houston Rockets" },
			{ k: "IND", v: "Indiana Pacers" },
			{ k: "LAC", v: "Los Angeles Clippers" },
			{ k: "LAL", v: "Los Angeles Lakers" },
			{ k: "MEM", v: "Memphis Grizzlies" },
			{ k: "MIA", v: "Miami Heat" },
			{ k: "MIL", v: "Milwaukee Bucks" },
			{ k: "MIN", v: "Minnesota Timberwolves" },
			{ k: "NOP", v: "New Orleans Pelicans" },
			{ k: "NYK", v: "New York Knicks" },
			{ k: "OKC", v: "Oklahoma City Thunder" },
			{ k: "ORL", v: "Orlando Magic" },
			{ k: "PHI", v: "Philadelphia 76ers" },
			{ k: "PHX", v: "Phoenix Suns" },
			{ k: "POR", v: "Portland Trail Blazers" },
			{ k: "SAC", v: "Sacramento Kings" },
			{ k: "SAS", v: "San Antonio Spurs" },
			{ k: "TOR", v: "Toronto Raptors" },
			{ k: "UTA", v: "Utah Jazz" },
			{ k: "WAS", v: "Washington Wizards" }
		]
};

var splitFiltersCustom = [
	{
		name : "CF1",
		activated: false,
		defaultValue : '',			
		label : "Create a custom filter 1",
		type : 'custom',
		visible: true,
		options : window.customFilterColumns
	},
	{
		name : "CF2",
		activated: false,
		defaultValue : '',			
		label : "Create a custom filter 2",
		type : 'custom',
		visible: true,
		options : window.customFilterColumns
	},
	{
		name : "CF3",
		activated: false,
		defaultValue : '',			
		label : "Create a custom filter 3",
		type : 'custom',
		visible: true,
		options : window.customFilterColumns
	},
	{
		name : "CF4",
		activated: false,
		defaultValue : '',			
		label : "Create a custom filter 4",
		type : 'custom',
		visible: true,
		options : window.customFilterColumns
	},
	{
		name : "CF5",
		activated: false,
		defaultValue : '',			
		label : "Create a custom filter 5",
		type : 'custom',
		visible: true,
		options : window.customFilterColumns
	}
];

var splitFilters = [
	{
		name: "GameSegment",
		label: "By Half",
		type: "select",
		description: "The option to view a player or team's stats in either the first half or the second half of a game.",
		visible: true,
		disabled: false,
		activated: false,
		defaultValue : 'All',
		initialValue : 'All',
		canSearch: false,
		options : [
			{k:"", v: "All"},
			{k:"First Half", v: "First Half"},
			{k: "Second Half", v:"Second Half"},
			{k: "Overtime", v:"Overtime"}
		]
	}, 
	{
		name: "Period",
		label: "By Period",
		type: "select",
		description: "The option to view a player or team's stats in either the first, second, third, or fourth quarter of a game.",
		visible: true,
		disabled: false,
		activated: false,
		defaultValue : '0',
		initialValue : '0',
		canSearch: true,
		options : [
			{k:"0", v: "All"},
			{k:"1", v: "1"},
			{k:"2", v: "2"},
			{k:"3", v: "3"},
			{k:"4", v: "4"},
			{k:"5", v: "OT 1"},
			{k:"6", v: "OT 2"},
			{k:"7", v: "OT 3"},
			{k:"8", v: "OT 4"},
			{k:"9", v: "OT 5"},
			{k:"10", v: "OT 6"},
			{k:"11", v: "OT 7"},
			{k:"12", v: "OT 8"},
			{k:"13", v: "OT 9"},
			{k:"14", v: "OT 10"},
		]
	}, 
	{
		name: "PlayerPosition",
		label: "Position",
		type: "select",
		description: "Filter out players by position to view either only Guards, Forwards, or Centers.",
		visible: true,
		disabled: false,
		activated: false,
		defaultValue : '',
		initialValue : '',
		canSearch: false,
		options : [
			{k:"", v: "All"},
			{k:"F", v: "Forward"},
			{k: "C", v:"Center"},
			{k: "G", v:"Guard"}
		]
	}, 
	{
		name: "StarterBench",
		label: "StarterBench",
		type: "select",
		description: "The option to view stats by either the starters or the bench of a team.",
		visible: true,
		disabled: false,
		activated: false,
		defaultValue : '',
		initialValue : '',
		canSearch: false,
		options : [
			{k:"", v: "All"},
			{k:"Starters", v: "Starters"},
			{k: "Bench", v:"Bench"}
		]
	}, 
	{
		name: "PlayerExperience",
		label: "Experience",
		type: "select",
		description: "The option to view either only rookies, or to exclude rookies from the data set.",
		visible: true,
		disabled: false,
		activated: false,
		defaultValue : '',
		initialValue : '',
		canSearch: false,
		options : [
			{k:"", v: "All"},
			{k:"Rookie", v: "Rookie"},
			{k: "Sophomore", v:"Sophomore"},
			{k: "Veteran", v:"Veteran"}
		]
	}, 
	{
		name: "OpponentTeamID",
		label: "VS Team",
		type: "select",
		description: "The option to view stats when a player or team plays a specific team.",
		visible: true,
		disabled: false,
		activated: false,
		defaultValue : '0',
		initialValue : '0',
		canSearch: true,
		options : [
			{k:"0", v: "All"},
			{k:"1610612737", v: "Atlanta Hawks"},
			{k:"1610612738", v: "Boston Celtics"},
			{k:"1610612751", v: "Brooklyn Nets"},
			{k:"1610612766", v: "Charlotte Bobcats"},
			{k:"1610612741", v: "Chicago Bulls"},
			{k:"1610612739", v: "Cleveland Cavaliers"},
			{k:"1610612742", v: "Dallas Mavericks"},
			{k:"1610612743", v: "Denver Nuggets"},
			{k:"1610612765", v: "Detroit Pistons"},
			{k:"1610612744", v: "Golden State Warriors"},
			{k:"1610612745", v: "Houston Rockets"},
			{k:"1610612754", v: "Indiana Pacers"},
			{k:"1610612746", v: "Los Angeles Clippers"},
			{k:"1610612747", v: "Los Angeles Lakers"},
			{k:"1610612763", v: "Memphis Grizzlies"},
			{k:"1610612748", v: "Miami Heat"},
			{k:"1610612749", v: "Milwaukee Bucks"},
			{k:"1610612750", v: "Minnesota Timberwolves"},
			{k:"1610612740", v: "New Orleans Pelicans"},
			{k:"1610612752", v: "New York Knicks"},
			{k:"1610612760", v: "Oklahoma City Thunder"},
			{k:"1610612753", v: "Orlando Magic"},
			{k:"1610612755", v: "Philadelphia 76ers"},
			{k:"1610612756", v: "Phoenix Suns"},
			{k:"1610612757", v: "Portland Trail Blazers"},
			{k:"1610612758", v: "Sacramento Kings"},
			{k:"1610612759", v: "San Antonio Spurs"},
			{k:"1610612761", v: "Toronto Raptors"},
			{k:"1610612762", v: "Utah Jazz"},
			{k:"1610612764", v: "Washington Wizards"}
		]
	}, 
	{
		name: "VsConference",
		label: "VS Conf",
		type: "select",
		description: "The option to view stats when a player or team plays either the Eastern or Western Conference.",
		visible: true,
		disabled: false,
		activated: false,
		defaultValue : '',
		initialValue : '',
		canSearch: false,
		options : [
			{k:"", v: "All"},
			{k:"East", v: "East"},
			{k: "West", v:"West"}
		]
	}, 
	{
		name: "VsDivision",
		label: "VS Division",
		type: "select",
		description: "The option to view stats when a player or team plays an individual division.",
		visible: true,
		disabled: false,
		activated: false,
		defaultValue : '',
		initialValue : '',
		canSearch: false,
		options : [
			{k:"", v: "All"},
			{k:"Atlantic", v: "Atlantic"},
			{k:"Central", v: "Central"},
			{k:"Northwest", v: "Northwest"},
			{k:"Pacific", v: "Pacific"},
			{k:"Southeast", v: "Southeast"}
		]
	}, 
	{
		name: "Outcome",
		label: "Outcome",
		type: "select",
		description: "The option to view a player or team's stats in either a team's wins or losses.",
		visible: true,
		disabled: false,
		activated: false,
		defaultValue : '',
		initialValue : '',
		canSearch: false,
		options : [
			{k:"", v: "All"},
			{k:"W", v: "Wins"},
			{k:"L", v: "Losses"}
		]
	},
	{
		name: "Location",
		label: "Location",
		type: "select",
		description: "The option to view a player or team's stats in either home or away games.",
		visible: true,
		disabled: false,
		activated: false,
		defaultValue : '',
		initialValue : '',
		canSearch: false,
		options : [
			{k:"", v: "All"},
			{k:"Home", v: "Home"},
			{k:"Road", v: "Road"}
		]
	},
	{
		name: "DateFrom",
		label: "From",
		type: "date",
		description: "The option to view a player or team's stats from a specific date in time.",
		visible: true,
		disabled: false,
		activated: false,
		defaultValue : '',
		initialValue : '',
		canSearch: false,
		options: [ ]
	}, 
	{
		name: "DateTo",
		label: "To",
		type: "date",
		description: "The option to view a player or team's stats to a specific date in time.",
		visible: true,
		disabled: false,
		activated: false,
		defaultValue : '',
		initialValue : '',
		canSearch: false,
		options: [ ]
	},
	{
		name: "SeasonSegment",
		label: "Season Segment",
		type: "select",
		description: "The option to view a player or team's stats Pre All Star Game or Post All Star Game.",
		visible: true,
		disabled: false,
		activated: false,
		defaultValue : '',
		initialValue : '',
		canSearch: false,
		options : [
			{k:"", v: "All"},
			{k:"Pre All-Star", v: "Pre All-Star"},
			{k:"Post All-Star", v: "Post All-Star"}
		]
	},
	{
		name: "Month",
		label: "Month",
		type: "select",
		description: "The option to view a player or team's stats in a specific month of the season.",
		visible: true,
		disabled: false,
		activated: false,
		defaultValue : '0',
		initialValue : '0',
		canSearch: true,
		options : [
			{k:"0", v: "All"},
			{k:"4",  v: "January"},
			{k:"5",  v: "February"},
			{k:"6",  v: "March"},
			{k:"7",  v: "April"},
			{k:"8",  v: "May"},
			{k:"9",  v: "June"},
			{k:"10", v: "July"},
			{k:"11", v: "August"},
			{k:"12", v: "September"},
			{k:"1",  v: "October"},
			{k:"2",  v: "November"},
			{k:"3",  v: "December"}
		]
	}, 
	{
		name: "LastNGames",
		label: "Last N Games",
		type: "select",
		description: "The option to view a player or team's stats in a specific amount of games prior.  In this filter, 'N' stands for the amount of games.",
		visible: true,
		disabled: false,
		canSearch: true,
		activated: false,
		defaultValue : '0',
		initialValue : '0',
		options : [
			{k:"0",  v: "All"},
			{k:"1",  v:"1"},{k:"2",  v:"2"},{k:"3",  v:"3"},{k:"4",  v:"4"},{k:"5",  v:"5"},
			{k:"6",  v:"6"},{k:"7",  v:"7"},{k:"8",  v:"8"},{k:"9",  v:"9"},{k:"10", v:"10"},
			{k:"11", v:"11"},{k:"12", v:"12"},{k:"13", v:"13"},{k:"14", v:"14"},{k:"15", v:"15"},
			{k:"16", v:"16"},{k:"17", v:"17"},{k:"18", v:"18"},{k:"19", v:"19"},{k:"20", v:"20"},
			{k:"21", v:"21"},{k:"22", v:"22"},{k:"23", v:"23"},{k:"24", v:"24"},{k:"25", v:"25"},
			{k:"26", v:"26"},{k:"27", v:"27"},{k:"28", v:"28"},{k:"29", v:"29"},{k:"30", v:"30"},
			{k:"31", v:"31"},{k:"32", v:"32"},{k:"33", v:"33"},{k:"34", v:"34"},{k:"35", v:"35"}
		]
	}, 
 	{
		name : "PlusMinus",
		label : "Differentials",
		type : 'select',
		description: "The option to view a player or team's stats as the difference from the league average.",
		visible: true,
		disabled: false,
		activated: false,
		defaultValue : 'N',
		initialValue : 'N',
		canSearch: false,
		options : [
			{k:"N", v: "Off"},
			{k:"Y", v: "On"}
		]
	}
	/*,	
 	{
		name : "Rank",
		label : "Rank",
		type : 'select',
		visible: true,
		disabled: false,
		activated: false,
		defaultValue : 'N',
		initialValue : 'N',
		canSearch: false,
		options : [
			{k:"N", v: "Off"},
			{k:"Y", v: "On"}
		]
	}*/
];